import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const appSource = await readFile(new URL("../public/app.js", import.meta.url), "utf8");
const serverSource = await readFile(new URL("../server.js", import.meta.url), "utf8");
const styles = await readFile(new URL("../public/styles.css", import.meta.url), "utf8");

assert.match(appSource, /import \{ validateStudyDocumentV1 \} from "\.\/js\/study-document-v1\.js/);
assert.match(appSource, /import \{ renderStudyDocumentV1ToHtml \} from "\.\/js\/study-document-v1-renderer\.js/);
assert.match(appSource, /studyDocumentPagePrompt/);
assert.match(appSource, /validateStudyDocumentPageBinding/);
assert.match(appSource, /officialStudyDocumentAnswers/);
assert.match(appSource, /validateOfficialStudyDocumentAnswerMapping/);
assert.match(appSource, /validateStudyDocumentTranslationV1/);
assert.match(appSource, /applyStudyDocumentTranslation/);
assert.match(appSource, /applyOfficialAnswerTranslation/);
assert.match(appSource, /function pageProcessingPanelHtml\(test, page\)/);
assert.match(appSource, /"Paste JSON"/);
assert.match(appSource, /<span>Copy Page Prompt<\/span>/);
assert.match(appSource, /<span>Copy Arabic Prompt<\/span>/);
assert.match(appSource, /Paste Arabic JSON/);
assert.match(appSource, /<span>Load JSON file<\/span>/);
assert.match(appSource, /<span>Validate &amp; Import<\/span>/);
assert.match(appSource, /study-document-summary-grid/);
assert.doesNotMatch(appSource, /View structure/);
assert.doesNotMatch(appSource, /study-document-structure/);
assert.doesNotMatch(appSource, /Advanced \/ Legacy Visual Builder/);
assert.doesNotMatch(appSource, /function legacyPageProcessingPanelHtml\(test, page\)/);
assert.doesNotMatch(appSource, /data-page-builder-step/);
assert.doesNotMatch(appSource, /visual-page-translation/);
assert.doesNotMatch(appSource, /AI pages/);
assert.doesNotMatch(appSource, /data-open-test-page-import-panel/);
assert.doesNotMatch(appSource, /data-open-test-page-translation-panel/);
assert.doesNotMatch(appSource, /data-import-test-pages/);
assert.doesNotMatch(appSource, /data-import-test-page-translation/);
assert.doesNotMatch(appSource, /Select source/);
assert.match(appSource, /studyDocument: parsed/);
assert.match(appSource, /ar: null/);
assert.match(appSource, /previous Arabic translation removed/);
assert.match(appSource, /if \(studyDocumentValidation\?\.valid\)/);
assert.match(appSource, /language === "ar" && !arabicTranslation/);
assert.match(appSource, /renderStudyDocumentV1ToHtml\(displayDocument/);
assert.match(appSource, /answers: semanticAnswers/);
assert.match(appSource, /showAnswers: state\.testPageOfficialAnswersVisible/);
assert.match(appSource, /function studyDocumentImportKind\(document\)/);
assert.match(appSource, /document\?\.schemaVersion === "study-document\/v1"/);
assert.match(appSource, /document\?\.schemaVersion === "study-document-translation\/v1"/);
assert.match(appSource, /function studyDocumentImportTarget\(document\)/);
assert.match(appSource, /page\.id === documentId \|\| page\?\.studyDocument\?\.documentId === documentId/);
assert.match(appSource, /const targetPage = target\.page/);
assert.match(appSource, /validateStudyDocumentTranslationV1\(parsed, targetPage\.studyDocument, semanticAnswers\)/);
assert.match(appSource, /validateStudyDocumentPageBinding\(parsed, targetPage\)/);
assert.match(appSource, /openImportedStudyDocumentPage\(saved\)/);
assert.match(appSource, /already has an English study document\. Replace it with this JSON\?/);
assert.doesNotMatch(appSource, /submitStudyDocumentDialogLegacy/);
assert.match(appSource, /editGraphics: true/);
assert.match(appSource, /function openStudyDocumentGraphicDialog\(nodeId\)/);
assert.match(appSource, /function initializeStudyDocumentGraphicCrop\(/);
assert.match(appSource, /data-study-document-graphic-crop-stage/);
assert.match(appSource, /data-save-study-document-graphic/);
assert.match(appSource, /study-document-graphics\/\$\{encodeURIComponent\(node\.id\)\}/);

const focusedPanelStart = appSource.indexOf("function pageProcessingPanelHtml(test, page)");
const focusedPanelEnd = appSource.indexOf("function studyDocumentNodeCount", focusedPanelStart);
const focusedPanelSource = appSource.slice(focusedPanelStart, focusedPanelEnd);
assert.doesNotMatch(focusedPanelSource, /page-builder-steps/);
assert.doesNotMatch(focusedPanelSource, /steps complete/);

assert.match(serverSource, /import \{ validateStudyDocumentV1 \} from "\.\/public\/js\/study-document-v1\.js"/);
assert.match(serverSource, /Invalid study-document\/v1 at/);
assert.match(serverSource, /Study document does not belong to this page/);
assert.match(serverSource, /validateOfficialStudyDocumentAnswerMapping/);
assert.match(serverSource, /officialStudyDocumentAnswers/);
assert.match(serverSource, /studyDocumentTranslation/);
assert.match(serverSource, /Invalid study-document Arabic translation/);
assert.match(serverSource, /studyDocumentChanged/);
assert.match(serverSource, /translationLanguagesToDelete/);
assert.match(serverSource, /delete nextTranslations\.ar/);
assert.match(serverSource, /normalized\.studyDocument = studyDocument/);
assert.match(serverSource, /delete existing\.studyDocument/);
assert.doesNotMatch(serverSource, /national-tests\/:testId\/pages\/import/);
assert.doesNotMatch(serverSource, /national-test-pages\/:pageId\/source-images/);
assert.doesNotMatch(serverSource, /national-test-pages\/:pageId\/source-page/);
assert.doesNotMatch(serverSource, /national-test-pages\/:pageId\/normalized-page/);
assert.match(serverSource, /national-test-pages\/:pageId\/study-document-graphics\/:nodeId/);
assert.match(serverSource, /studyDocumentGraphicUpload\.single\("image"\)/);
assert.match(serverSource, /node\.placeholder = false/);
assert.match(serverSource, /node\.placeholder = true/);

assert.match(styles, /\.study-document-overview/);
assert.match(styles, /\.study-document-summary-grid\.has-arabic-card/);
assert.doesNotMatch(styles, /\.study-document-structure/);
assert.doesNotMatch(styles, /\.study-document-json-display/);
assert.match(styles, /\.study-document-dialog::backdrop/);
assert.match(styles, /\.study-document-validation-message\.invalid/);
assert.match(styles, /\.study-document-choice-control/);
assert.match(styles, /\.study-document-choice-row/);
assert.match(styles, /grid-template-columns: minmax\(0, 1fr\) 12px/);
assert.match(styles, /padding-inline-start: 24px/);
assert.match(styles, /\.study-document-graphic--editable/);
assert.match(styles, /\.study-document-graphic-crop-stage/);
assert.match(styles, /\.study-document-graphic-crop-selection/);
assert.doesNotMatch(styles, /\.page-builder-/);

console.log("study-document/v1 UI integration tests passed");
